# Site settings
title: A Blog for Blobs
header-img: img/home-bg.jpg
email: sschadwick@gmail.com
description: "Personal tech blog"
baseurl: ""
url: "http://104.131.138.183/"
twitter_username:
github_username:  sschadwick
facebook_username:

# Build settings
gems: [jekyll-paginate]
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
